# Generated by Django 4.2.7 on 2025-08-05 14:06

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(help_text='Title of the memory', max_length=255)),
                ('content', models.TextField(help_text='Detailed content/description of the memory')),
                ('visit_date', models.DateField(blank=True, help_text='Date when the user visited this place', null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether this memory is visible to other users')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Tags associated with this memory', size=None)),
                ('location', models.OneToOneField(blank=True, help_text='Location associated with this memory (1-1 relationship)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='locations.location')),
                ('user', models.ForeignKey(help_text='User who created this memory', on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mm_memories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='memories.memory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mm_memory_likes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='mm_memory_l_user_id_83ff9c_idx'), models.Index(fields=['memory'], name='mm_memory_l_memory__fec19d_idx'), models.Index(fields=['created_at'], name='mm_memory_l_created_5a06f9_idx')],
                'unique_together': {('user', 'memory')},
            },
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user'], name='mm_memories_user_id_fe4a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['location'], name='mm_memories_locatio_527bca_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['is_public'], name='mm_memories_is_publ_dd4fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['visit_date'], name='mm_memories_visit_d_b09aca_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['title'], name='mm_memories_title_9905a1_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['created_at'], name='mm_memories_created_c4a5c4_idx'),
        ),
    ]
