# Generated by Django 4.2.7 on 2025-08-05 14:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='Name of the shop item', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the shop item')),
                ('image_base64', models.TextField(help_text='Base64 encoded image data URL for the item')),
                ('price', models.BigIntegerField(help_text='Price in virtual currency (Xu)', validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.PositiveIntegerField(default=0, help_text='Available stock quantity')),
                ('item_type', models.CharField(choices=[('marker', 'Marker'), ('decoration', 'Decoration'), ('theme', 'Theme'), ('effect', 'Effect')], default='marker', help_text='Type of item', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is available for purchase')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the item')),
            ],
            options={
                'db_table': 'mm_shop_items',
                'ordering': ['item_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity owned by user', validators=[django.core.validators.MinValueValidator(1)])),
                ('shop_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_items', to='shop.shopitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mm_user_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('purchase', 'Purchase'), ('admin_add', 'Admin Add'), ('admin_subtract', 'Admin Subtract'), ('refund', 'Refund'), ('bonus', 'Bonus')], help_text='Type of transaction', max_length=50)),
                ('amount', models.BigIntegerField(help_text='Transaction amount (positive for add, negative for subtract)')),
                ('description', models.TextField(blank=True, help_text='Description of the transaction')),
                ('quantity', models.PositiveIntegerField(blank=True, help_text='Quantity of items purchased (if applicable)', null=True)),
                ('balance_before', models.BigIntegerField(help_text='User balance before transaction')),
                ('balance_after', models.BigIntegerField(help_text='User balance after transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, help_text='Admin user who performed the transaction (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_transactions', to=settings.AUTH_USER_MODEL)),
                ('shop_item', models.ForeignKey(blank=True, help_text='Shop item involved in transaction (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='shop.shopitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mm_transaction_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shopitem',
            index=models.Index(fields=['item_type'], name='mm_shop_ite_item_ty_f9f822_idx'),
        ),
        migrations.AddIndex(
            model_name='shopitem',
            index=models.Index(fields=['is_active'], name='mm_shop_ite_is_acti_efe410_idx'),
        ),
        migrations.AddIndex(
            model_name='shopitem',
            index=models.Index(fields=['price'], name='mm_shop_ite_price_718807_idx'),
        ),
        migrations.AddIndex(
            model_name='shopitem',
            index=models.Index(fields=['stock'], name='mm_shop_ite_stock_256d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='useritem',
            index=models.Index(fields=['user'], name='mm_user_ite_user_id_8b2561_idx'),
        ),
        migrations.AddIndex(
            model_name='useritem',
            index=models.Index(fields=['shop_item'], name='mm_user_ite_shop_it_0dc80a_idx'),
        ),
        migrations.AddIndex(
            model_name='useritem',
            index=models.Index(fields=['quantity'], name='mm_user_ite_quantit_22a4ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useritem',
            unique_together={('user', 'shop_item')},
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['user'], name='mm_transact_user_id_16947f_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['admin'], name='mm_transact_admin_i_14fcc3_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['type'], name='mm_transact_type_70b385_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['shop_item'], name='mm_transact_shop_it_a21fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['created_at'], name='mm_transact_created_cefb17_idx'),
        ),
    ]
