# Generated by Django 4.2.7 on 2025-08-05 14:06

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='Name of the location', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the location')),
                ('latitude', models.DecimalField(decimal_places=8, help_text='Latitude coordinate (-90 to 90)', max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=8, help_text='Longitude coordinate (-180 to 180)', max_digits=11, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Point geometry for geospatial queries', null=True, srid=4326)),
                ('address', models.TextField(blank=True, help_text='Full address of the location')),
                ('country', models.CharField(blank=True, help_text='Country name', max_length=100)),
                ('city', models.CharField(blank=True, help_text='City name', max_length=100)),
                ('marker_item', models.ForeignKey(blank=True, help_text='Custom marker item for this location (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_using_marker', to='shop.shopitem')),
                ('user', models.ForeignKey(help_text='User who created this location', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mm_locations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='mm_location_user_id_68eef9_idx'), models.Index(fields=['country'], name='mm_location_country_cf7f06_idx'), models.Index(fields=['city'], name='mm_location_city_ea28dd_idx'), models.Index(fields=['marker_item'], name='mm_location_marker__c7b432_idx'), models.Index(fields=['latitude', 'longitude'], name='mm_location_latitud_da0d1d_idx')],
            },
        ),
    ]
